project:
  type: website
  resources:
    - CNAME
  output-dir: docs

website:
  title: "Poker Camp"
  open-graph: true
  # google-analytics: 
  favicon: ./assets/favicon32.png
  twitter-card:
    creator: "@pokercamporg"
  navbar: 
    logo: ./assets/favicon32.png
    background: primary
    left: 
      - sidebar:signup
      - text: "AI Poker Camp"
        href: /aicamp
      - text: "Poker Camp"
        href: /camp
    right: 
      - text: "About"
        href: about.qmd

    tools: 
      - icon: mailbox2-flag
        href: https://forms.gle/xx1tZNbwpYBLASmQ8
      - icon: discord
        href: https://discord.gg/ATg5HQpZ
      - icon: twitter
        href: https://x.com/pokercamporg
      - icon: github
        href: https://github.com/chisness/pokercamp
  sidebar: 
    - id: aipcs24
      title: "Poker Camp"
      style: "docked"
      background: light
      contents:
        - logo: /assets/pcicon.png
        - section: "Challenges"
          contents:
            - text: "1: Kuhn Poker"
            - text: "2: Perfect Info Games"
            - text: "3: Leduc Poker"
            - text: "4: Rock Paper Scissors"
            - text: "5: Texas Tac Toe"
            - text: "6: Rock Poker Scissors"
        - section: "Configuration"
          contents:
            - text: "General Setup"
            - text: "Building and Running Bots"
        - section: "About the Course"
          contents:
            - text: "Meetings and Challenges"
            - text: "Instructors and TAs"
    - id: signup
      title: "Signup"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - text: "AI Poker Camp 2024 SF Summer Beta"
          href: /signup
  # sidebar:
  #   style: docked
  #   background: light
  #   contents: 

format:
  html:
    theme: cerulean
    math: true 
    toc: true
    toc-expand: true
    mathjax: 
      config: 
        text: 
          inlineMath: [['$', '$'], ['\\(', '\\)']]