project:
  type: website
  resources:
    - CNAME
  output-dir: docs

website:
  title: "Poker Camp"
  page-footer: "© 2024 pokercamp.org. All rights reserved."
  open-graph: true
  google-analytics: "G-1R1JQVQ05N"
  favicon: ./assets/favicon32.png
  twitter-card:
    creator: "@pokercamporg"
  navbar: 
    logo: ./assets/favicon32.png
    background: primary
    left: 
      # - sidebar:signup
      - text: "Signup: AI Poker Camp Summer 2024"
        href: /signup
      - sidebar:campinfo
      # - text: "AI Poker Camp Info"
      #   href: /aicamp
      # - text: "Poker and Applied Rationality Camp Info"
      #   href: /camp
    right: 
      - text: "About"
        href: about.qmd

    tools: 
      - icon: mailbox2-flag
        href: https://forms.gle/xx1tZNbwpYBLASmQ8
      - icon: discord
        href: https://discord.gg/ATg5HQpZ
      - icon: twitter
        href: https://x.com/pokercamporg
      - icon: github
        href: https://github.com/chisness/pokercamp
  sidebar: 
    - id: aipcs24
      style: "docked"
      background: light
      contents:
        - text: "AIPC Summer 2024"
          href: "/aipcs24"
        - section: "Challenges"
          contents:
            - section: "#1: Kuhn Poker"
              contents: 
                - text: "Optional Reading"
                  href: "aipcs24/1kuhn_reading.qmd"
                - text: "Rules"
                  href: "aipcs24/1kuhn_rules.qmd"
                - text: "Challenge"
                  href: "aipcs24/1kuhn_challenge.qmd"
                - text: "Challenge Review"
                  # href: "aipcs24/1kuhn_challenge_review.qmd"
            # - section: "#2: Other Games"
            #   contents:
            #     - text: "Reading"
            #       href: "aipcs24/2othergames_reading.qmd"
            #     - text: "Challenge"
            #       href: "aipcs24/2othergames_challenge.qmd"
            #     - text: "Challenge Review"
            #       href: "aipcs24/2othergames_challenge_review.qmd"
            - section: "#2: Leduc Poker"
              contents:
                - text: "Class Materials"
                  # href: "aipcs24/3leduc_reading1.qmd"
                # - text: "Reading 2"
                  # href: "aipcs24/3leduc_reading2.qmd"
                - text: "Challenge"
                  # href: "aipcs24/3leduc_challenge.qmd"
                - text: "Challenge Review"
                  # href: "aipcs24/3leduc_challenge_review.qmd"
            - section: "#3: Rock Paper Scissors"
              contents:
                - text: "Class Materials"
                  # href: "aipcs24/4rps_reading1.qmd"
                # - text: "Reading 2"
                  # href: "aipcs24/4rps_reading2.qmd"
                - text: "Challenge"
                  # href: "aipcs24/4rps_challenge.qmd"
                - text: "Challenge Review"
                  # href: "aipcs24/4rps_challenge_review.qmd"
            - section: "#4: Texas Tac Toe"
              contents:
                - text: "Class Materials"
                  # href: "aipcs24/5ttt_reading1.qmd"
                # - text: "Reading 2"
                  # href: "aipcs24/5ttt_reading2.qmd"
                - text: "Challenge"
                  # href: "aipcs24/5ttt_challenge.qmd"
                - text: "Challenge Review"
                  # href: "aipcs24/5ttt_challenge_review.qmd"
            - section: "#5: Rock Poker Scissors"
              contents:
                - text: "Class Materials"
                  # href: "aipcs24/6rps_reading1.qmd"
                # - text: "Reading 2"
                  # href: "aipcs24/6rps_reading2.qmd"
                - text: "Challenge"
                  # href: "aipcs24/6rps_challenge.qmd"
                - text: "Challenge Review"
                  # href: "aipcs24/6rps_challenge_review.qmd"        
        - section: "Configuration"
          contents:
            - text: "General Setup"
              # href: "aipcs24/setup.qmd"
            - text: "Building and Running Bots"
              # href: "aipcs24/bots.qmd"
        - section: "About the Course"
          contents:
            - text: "Sessions and Challenges"
              href: "aipcs24/sessions.qmd"
            - text: "Instructors and TAs"
              # href: "aipcs24/staff.qmd"
    - id: campinfo
      title: "Camp Info"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - text: "Poker and Applied Rationality Camp"
          href: /camp
        - text: "AI Poker Camp"
          href: /aicamp
    # - id: signup
    #   title: "Signup"
    #   style: "docked"
    #   background: light
    #   collapse-level: 2
    #   contents: 
    #     - text: "AI Poker Camp 2024 SF Summer Beta"
    #       href: /signup
  # sidebar:
  #   style: docked
  #   background: light
  #   contents: 

format:
  html:
    theme: cerulean
    math: true 
    toc: true
    toc-expand: true
    mathjax: 
      config: 
        text: 
          inlineMath: [['$', '$'], ['\\(', '\\)']]