project:
  type: website
  output-dir: docs

website:
  title: "Poker Camp"
  open-graph: true
  # google-analytics: 
  # favicon: ./assets/pcicon.png
  twitter-card:
    creator: "@pokercamporg"
  navbar: 
    background: primary
    left: 
      - text: "AI Poker Camp July SF Signup"
        href: https://poker.camp/signup
      - text: "AI Poker Camp"
        href: https://poker.camp/aicamp
      - text: "Poker Camp"
        href: https://poker.camp/camp
    right: 
      - text: "About"
        href: about.qmd
    tools: 
      - icon: twitter
        href: https://x.com/pokercamporg
      - icon: github
        href: https://github.com/chisness/pokercamp
  # sidebar:
  #   style: docked
  #   background: light
  #   contents: 

format:
  html:
    theme: cerulean
    math: true 
    toc: true
    toc-expand: true
    mathjax: 
      config: 
        text: 
          inlineMath: [['$', '$'], ['\\(', '\\)']]