project:
  type: website
  resources:
    - CNAME
  output-dir: docs

website:
  title: "Poker Camp"
  open-graph: true
  # google-analytics: 
  favicon: ./assets/favicon32.png
  twitter-card:
    creator: "@pokercamporg"
  navbar: 
    logo: ./assets/favicon32.png
    background: primary
    left: 
      - sidebar:signup
      - text: "AI Poker Camp"
        href: /aicamp
      - text: "Poker Camp"
        href: /camp
    right: 
      - text: "About"
        href: about.qmd

    tools: 
      - icon: mailbox2-flag
        href: https://forms.gle/xx1tZNbwpYBLASmQ8
      - icon: discord
        href: https://discord.gg/ATg5HQpZ
      - icon: twitter
        href: https://x.com/pokercamporg
      - icon: github
        href: https://github.com/chisness/pokercamp
  sidebar: 
    # - id: id-camp
    #   title: "Poker Camp"
    #   style: "docked"
    #   background: light
    #   contents:
    #     - text: "test1"
    #     - text: "test2"
    #     - about.qmd
    - id: signup
      title: "Signup"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - text: "AI Poker Camp July IRL in SF"
          href: /signup
  # sidebar:
  #   style: docked
  #   background: light
  #   contents: 

format:
  html:
    theme: cerulean
    math: true 
    toc: true
    toc-expand: true
    mathjax: 
      config: 
        text: 
          inlineMath: [['$', '$'], ['\\(', '\\)']]