project:
  type: website
  resources:
    - CNAME
  output-dir: docs

website:
  title: "Poker Camp"
  page-footer: "© 2024 poker.camp. All rights reserved."
  open-graph: true
  google-analytics: "G-1R1JQVQ05N"
  favicon: ./assets/favicon32.png
  twitter-card:
    creator: "@pokercamporg"
  navbar: 
    logo: ./assets/favicon32.png
    background: primary
    left: 
      # - sidebar:signup
      # - text: "Signup: AI Poker Camp Summer 2024"
      #   href: /signup
      - sidebar:campinfo
      # - text: "AI Poker Camp Info"
      #   href: /aicamp
      # - text: "Poker and Applied Rationality Camp Info"
      #   href: /camp
    right: 
      - text: "About"
        href: about.qmd

    tools: 
      - icon: mailbox2-flag
        href: https://forms.gle/xx1tZNbwpYBLASmQ8
      - icon: discord
        href: https://discord.gg/KZQK2xN8Da
      - icon: twitter
        href: https://x.com/pokercamporg
      - icon: github
        href: https://github.com/chisness/pokercamp
  sidebar: 
    - id: rps-hackathon-fractal
      style: "docked"
      background: light
      contents:
        - text: "RPS Hackathon @ Fractal"
          href: "/rps-hackathon-fractal"
        - section: "Getting Started"
          contents: 
            - text: "Hackathon Instructions"
              href: "rps-hackathon-fractal/instructions.qmd"
            - text: "Guide to Building a Bot"
              href: "rps-hackathon-fractal/botguide.qmd"
        - section: "Hackathon"
          contents: 
            - text: "Login with GitHub"
              href: "login/index.qmd"
            - text: "Submit Your Bot"
              href: "rps-hackathon-fractal/botsubmit.qmd"
            - text: "Leaderboard"
              href: "rps-hackathon-fractal/leaderboard.qmd"
            - text: "Test Results"
              href: "rps-hackathon-fractal/testing.qmd"
    - id: odpcf24
      style: "docked"
      background: light
      contents:
        - text: "ODPC Fall 2024"
          href: "/odpcf24"
        - section: "Sessions"
          contents: 
            - text: "#1: Thinking in Bets"
              href: "odpcf24/thinkinginbets.qmd"
            - text: "#2: Expected Value"
              href: "odpcf24/expectedvalue.qmd"
            - text: "#3: Game Theory"
              href: "odpcf24/gametheory.qmd"
            - text: "#4: Changing Your Mind"
              href: "odpcf24/changingyourmind.qmd"
            - text: "#5: Risk and Luck"
              href: "odpcf24/riskandluck.qmd"
            - text: "#6: Predicting the Future"
              href: "odpcf24/predictingthefuture.qmd"
    - id: aipcs24
      style: "docked"
      background: light
      contents:
        - text: "AIPC Summer 2024"
          href: "/aipcs24"
        - section: "Challenges"
          contents:
            - section: "#1: Kuhn Poker"
              contents: 
                - text: "Optional Reading"
                  href: "aipcs24/1kuhn_reading.qmd"
                - text: "Rules"
                  href: "aipcs24/1kuhn_rules.qmd"
                - text: "Challenge"
                  href: "aipcs24/1kuhn_challenge.qmd"
                - text: "Challenge Review"
                  # href: "aipcs24/1kuhn_challenge_review.qmd"
            # - section: "#2: Other Games"
            #   contents:
            #     - text: "Reading"
            #       href: "aipcs24/2othergames_reading.qmd"
            #     - text: "Challenge"
            #       href: "aipcs24/2othergames_challenge.qmd"
            #     - text: "Challenge Review"
            #       href: "aipcs24/2othergames_challenge_review.qmd"
            - section: "#2: Leduc Poker"
              contents:
                - text: "Class Materials"
                  href: "aipcs24/2leduc_class.qmd"
                # - text: "Reading 2"
                  # href: "aipcs24/3leduc_reading2.qmd"
                - text: "Challenge"
                  href: "aipcs24/2leduc_challenge.qmd"
                - text: "Leaderboard"
                  href: "aipcs24/2leduc_leaderboard.qmd"
                - text: "Challenge Review"
                  # href: "aipcs24/2leduc_challenge_review.qmd"
            - section: "#3: Rock Paper Scissors"
              contents:
                - text: "Class Materials"
                  href: "aipcs24/3rps_reading.qmd"
                # - text: "Reading 2"
                  # href: "aipcs24/3rps_reading2.qmd"
                - text: "Challenge"
                  href: "aipcs24/3rps_challenge.qmd"
                - text: "Leaderboard"
                  href: "aipcs24/3rps_leaderboard.qmd"
                - text: "Challenge Review"
                  # href: "aipcs24/3rps_challenge_review.qmd"
            - section: "#4: Royal Hold'em"
              contents:
                - text: "Class Materials"
                  href: "aipcs24/4nlrhe_reading.qmd"
                # - text: "Reading 2"
                  # href: "aipcs24/4ttt_reading2.qmd"
                - text: "Challenge"
                  # href: "aipcs24/4ttt_challenge.qmd"
                - text: "Challenge Review"
                  # href: "aipcs24/4ttt_challenge_review.qmd"
            - section: "#5: Coming soon..."
              contents:
                - text: "Class Materials"
                  # href: "aipcs24/5rps_reading.qmd"
                # - text: "Reading 2"
                  # href: "aipcs24/6rps_reading2.qmd"
                - text: "Challenge"
                  # href: "aipcs24/5rps_challenge.qmd"
                - text: "Challenge Review"
                  # href: "aipcs24/5rps_challenge_review.qmd"        
        - section: "Configuration"
          contents:
            - text: "General Setup"
              # href: "aipcs24/setup.qmd"
            - text: "Building and Running Bots"
              href: "aipcs24/bots.qmd"
            - text: "Building and Running Solvers"
              href: "aipcs24/solvers.qmd"
        - section: "About the Course"
          contents:
            - text: "Sessions and Challenges"
              href: "aipcs24/sessions.qmd"
            - text: "Instructors and TAs"
              # href: "aipcs24/staff.qmd"
    - id: campinfo
      title: "Camp Info"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - text: "Poker and Applied Rationality Camp (PAR)"
          href: /camp
        - text: "AI Poker Camp (AIPC)"
          href: /aicamp
    # - id: signup
    #   title: "Signup"
    #   style: "docked"
    #   background: light
    #   collapse-level: 2
    #   contents: 
    #     - text: "AI Poker Camp 2024 SF Summer Beta"
    #       href: /signup
  # sidebar:
  #   style: docked
  #   background: light
  #   contents: 

format:
  html:
    theme: cerulean
    bread-crumbs: false
    math: true 
    toc: true
    toc-expand: true
    mathjax: 
      config: 
        text: 
          inlineMath: [['$', '$'], ['\\(', '\\)']]