project:
  type: website
  resources:
    - CNAME
  output-dir: docs

website:
  title: "Poker Camp"
  open-graph: true
  google-analytics: "G-1R1JQVQ05N"
  favicon: ./assets/favicon32.png
  twitter-card:
    creator: "@pokercamporg"
  navbar: 
    logo: ./assets/favicon32.png
    background: primary
    left: 
      # - sidebar:signup
      - text: "Signup: AI Poker Camp Summer 2024"
        href: /signup
      - sidebar:campinfo
      # - text: "AI Poker Camp Info"
      #   href: /aicamp
      # - text: "Poker and Applied Rationality Camp Info"
      #   href: /camp
    right: 
      - text: "About"
        href: about.qmd

    tools: 
      - icon: mailbox2-flag
        href: https://forms.gle/xx1tZNbwpYBLASmQ8
      - icon: discord
        href: https://discord.gg/ATg5HQpZ
      - icon: twitter
        href: https://x.com/pokercamporg
      - icon: github
        href: https://github.com/chisness/pokercamp
  sidebar: 
    - id: aipcs24
      style: "docked"
      background: light
      contents:
        - text: "AIPC Summer 2024"
          href: "/aipcs24"
        - section: "Challenges"
          contents:
            - text: "1: Kuhn Poker"
              href: "aipcs24/challenge1kuhn.qmd"
            - text: "2: Other Games"
              href: "aipcs24/challenge2othergames.qmd"
            - text: "3: Leduc Poker"
              href: "aipcs24/challenge3leduc.qmd"
            - text: "4: Rock Paper Scissors"
              href: "aipcs24/challenge4rps.qmd"
            - text: "5: Texas Tac Toe"
              href: "aipcs24/challenge5ttt.qmd"
            - text: "6: Rock Poker Scissors"
              href: "aipcs24/challenge6rps.qmd"
        - section: "Configuration"
          contents:
            - text: "General Setup"
              href: "aipcs24/setup.qmd"
            - text: "Building and Running Bots"
              href: "aipcs24/bots.qmd"
        - section: "About the Course"
          contents:
            - text: "Meetings and Challenges"
              href: "aipcs24/meetings.qmd"
            - text: "Instructors and TAs"
              href: "aipcs24/staff.qmd"
    - id: campinfo
      title: "Camp Info"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - text: "Poker and Applied Rationality Camp"
          href: /camp
        - text: "AI Poker Camp"
          href: /aicamp
    # - id: signup
    #   title: "Signup"
    #   style: "docked"
    #   background: light
    #   collapse-level: 2
    #   contents: 
    #     - text: "AI Poker Camp 2024 SF Summer Beta"
    #       href: /signup
  # sidebar:
  #   style: docked
  #   background: light
  #   contents: 

format:
  html:
    theme: cerulean
    math: true 
    toc: true
    toc-expand: true
    mathjax: 
      config: 
        text: 
          inlineMath: [['$', '$'], ['\\(', '\\)']]