---
title: "AI Poker Camp (2024 Summer Beta SF)"
format:
  html:
    math: true
---

::: {.callout-note appearance="default"}

## Sign up now! 

**[Signup Form](https://forms.gle/72yqxC3UpP9aa2wv7)**

- After signing up, we'll be in touch with all details

- The beta program is free! 

<!-- - The cost for the camp is $100 per person with an optional $20 pre-camp Poker Basics workshop.

- After signing up, we'll be in touch with all details including payment options. -->
:::

## When?
6pm-8pm Mondays and Thursdays, July 15 through August 15.

## What?
A five-week, twice-weekly course on applied game theory through you writing AIs to play games. By the end, you should be able to write an AI to play poker.

This is a beta test of a course we’re planning to run online in the fall, so it’ll be small. We’ll cap signups somewhere between 16 and 24 students.

## Where?
Strictly in-person in San Francisco. Location to be announced.

### Wait, really? I can’t make that!
We’re also planning to run an online version of the course starting in late September. You can join our [mailing list](https://docs.google.com/forms/d/e/1FAIpQLSep2wLWyYzyBt2tBxCjlhEzUmMfSu8iVRRT2Zs5C5GUf_F3gw/viewform) to learn more when it’s announced.

## Who?

- We recommend students be able to program in Python and [perform a Bayesian update](https://towardsdatascience.com/bayesian-updating-simply-explained-c2ed3e563588) (though it’s fine to lean on an LLM for help on either).

- Knowledge of the game of poker is not necessary. (We are offering a 2 hour Poker Basics workshop on Sun Jul 7.)

## What’s the curriculum?
The course is built around six or seven practical challenges – think “kaggle competition for game-playing programs”. These will cover:

- Tutorial: One-card / Kuhn Poker

  - Topic: Algorithms for solving incomplete-information games.

- Larger one-card poker formats and other simple games

  - Topic: Scaling up algorithms to larger game trees.

- Rock-Paper-Scissors against imperfect opponents

  - Topic: Techniques for modeling empirical opponent behavior.

- Hidden-information version of [Probabilistic Tic-Tac-Toe](https://www.csun.io/2024/06/08/probabilistic-tic-tac-toe.html)

  - Topic: Modeling hidden information from opponent actions.

- [Texas Holdem with simplified betting](https://manifoldmarkets.notion.site/Rock-Paper-Scissors-Poker-a77d63a1537941ebb15f8f81194dbabb)
  - Topic: Putting it together!

We’re intending for the Summer Beta to have about the intensity of one (1) college course in applied CS. You should expect to make at least 9 out of 10 class sessions.

## Who’s teaching?
**[Ross Rheingans-Yoo](https://twitter.com/_rossry)** wrote the advanced trading simulations for the Jane Street trading internship program from 2018 to 2021.

**Max Chiswick** is a former poker pro who has played more than 10 million hands of online poker, and created [AI Poker Tutorial](https://aipokertutorial.com).

**[Ricki Heicklen](https://rickiheicklen.com/)** is a curriculum advisor (but will not be teaching in the SF Beta).

## How?
**[Signup Form](https://forms.gle/72yqxC3UpP9aa2wv7)**

- After signing up, we'll be in touch with all details

- The beta program is free! 

<!-- - The cost for the camp is $100 per person with an optional $20 pre-camp Poker Basics workshop on Sun Jul 7. -->

<!-- - After signing up, we'll be in touch with all details including payment options. If financially prohibitive, you can let us know and we’ll try to work something out. -->

## Something else?
[Get in touch!](mailto:info@poker.camp)